src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 1000, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\ManyToOne(inversedBy: 'events')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $User = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }
}

templates/inc/foot.html.twig
<div class=footer>
    BasArtisanGestion - programme par Marlon Bas réalisé pour Lodewijk Bas, Artisan - 2023 - publié sous licence GPL-3.0
</div>

templates/inc/nav.html.twig
<nav class="navbar">
    <div class="navbar__container">
    {% if app.user %}
        <a href="{{ path('app_main') }}" id="navbar_title">{{app.user.nom}}</a>
        <ul class="navbar__menu">
            <li class="navbar__btn small-stack">
                <a href="{{ path('app_logout') }}" class="button">déconnexion</a>
            </li>
            <li class="navbar__btn small-stack">
                <a href="{{ path('app_parametres') }}" class="button">paramètres</a>
            </li>
        </ul>
    {% endif %}
    </div>
</nav>